version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "84:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=main.settings